### PR TITLE
pin boost

### PR DESCRIPTION
**Pull request by ocefpaf**

### CODE REVIEW

**Comment by jschueller** [comment]
Why does swig depend on boost ?

**Comment by ocefpaf** [comment]
> Why does swig depend on boost?

No idea but you were the one who changed from `boost` to `boos-cpp`, so I guess you are more qualified to answer that than me :wink: 

See https://github.com/conda-forge/swig-feedstock/commit/41a040e42c580d8de7d14c1ac08065066adf7624

Anyways, the lack of pinning here and its dependency at run time is causing trouble downstream and pullin packages from `defaults` instead of `conda-forge`. We need to either remove the dependency or pin it properly.

**Comment by jschueller** [comment]
@jakirkham @msarahan do we know why swig depends on boost ?

**Comment by jakirkham** [comment]
I think SWIG detected that Boost was available and would optionally use it in making bindings. Though it has been a while since I looked into this and don't really have time to dig up info on it ATM.

There really is no need to pin it. SWIG isn't linking to Boost. In fact, one user requested we unpin it last time it was pinned and went to the effort of removing it. ( https://github.com/conda-forge/swig-feedstock/issues/2 ) ( https://github.com/conda-forge/swig-feedstock/pull/3 ) So wouldn't recommend doing this.

**Comment by ocefpaf** [comment]
I am thinking about the ecosystem health here and not being selfish about `swig`. If that is dependency can be remove it would be even better.

**Pull request merged**
