### PR TITLE
Rerun jobs

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jakirkham** [comment]
What is wrong? Have you tried restarting the CIs?

**Comment by jakirkham** [comment]
Have restarted the CIs on the feedstock. Though you should have access to them too as you are a maintainer. Please let me know if that is not the case.

**Comment by jschueller** [comment]
@jakirkham ok, I wanted to make sure.

**Comment by jakirkham** [comment]
Of course. Thanks for letting me know.

**Comment by jschueller** [comment]
@jakirkham, it's weird, the linux worker got a timeout when testing (running ```swig -help```)

**Comment by jakirkham** [comment]
Looks like it failed when starting tests to me. 😕

In any event, restarted again and it appears to have worked this last time.

**Pull request closed without merging**
