### PR TITLE
Build long prefix package using conda-build 2.x

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jschueller** [comment]
shouldn't this be reported to conda smithy ? next time i'll rerender your changes will be gone

**Comment by jjhelmus** [comment]
> shouldn't this be reported to conda smithy ? next time i'll rerender your changes will be gone

Yes, rerendering will remove these changes, but that is the idea.  Before moving all of `conda-forge` to using `conda build` `2.x`, packages with short binary prefixes, like swig, need to be rebuild to support long prefixes.  This is being done manually so as to not disrupt the rest of the organization until the switch can be made.

The plan is once most (all?) of the short binary prefix packages have been rebuilt then `conda-forge-build-setup` will be updated to use `conda build` 2.x.  Until then `conda build` will be kept pinned at `1.x`

More details can be found in conda-forge/conda-forge-build-setup-feedstock#40.

**Comment by jakirkham** [comment]
As Jonathan has already said, this is meant to be a temporary change as part of prepping for switching to `conda-build` version `2.0.x`.

I'm ok with seeing this merged.

Any other concerns @jschueller ? If not, would you like to do the honors?

**Comment by jjhelmus** [comment]
Thanks all, glad this build made in into `conda-forge`!

**Pull request merged**
